server:
  port: 8080


spring:
  #  服务名称
  application:
    name: huizhi-gateway
  # oauth
  security.oauth2.resourceserver.jwt.jwk-set-uri: 'http://localhost:8081/.well-known/jwks.json'
  cloud:
    zookeeper:
      discovery:
        enabled: true
        register: true
      connect-string: 127.0.0.1:2181

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true


